SHELL := /bin/bash
PYTHON ?= python3
PY := $(PYTHON)

VENV := .venv
BIN := $(VENV)/bin
PIP := $(BIN)/pip
PYTEST := $(BIN)/pytest
RUFF := $(BIN)/ruff
BLACK := $(BIN)/black
MYPY := $(BIN)/mypy
ALEMBIC := $(BIN)/alembic
PYTHONPATH_BACKEND := PYTHONPATH=backend

.PHONY: help setup install dev test lint format check migrate revision db-up db-down \
        docker-up docker-down etl-run clean

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-14s\033[0m %s\n", $$1, $$2}'

setup: ## Create virtualenv and install dev deps
	$(PYTHON) -m venv $(VENV)
	$(PIP) install --upgrade pip
	$(PIP) install -r requirements-dev.txt
	$(BIN)/pre-commit install

install: ## Install runtime deps into current environment
	$(PIP) install -r requirements.txt

dev: ## Run the FastAPI dev server (auto-reload)
	$(PYTHONPATH_BACKEND) $(BIN)/uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

test: ## Run the test suite
	$(PYTHONPATH_BACKEND) $(PYTEST) --cov=app --cov-report=term-missing

lint: ## Lint with ruff
	$(RUFF) check backend etl scripts tests

format: ## Auto-format with black
	$(BLACK) --line-length=100 backend etl scripts tests

format-check: ## Check formatting without changing files
	$(BLACK) --line-length=100 --check backend etl scripts tests

typecheck: ## Static type checking with mypy
	$(MYPY) backend/app

check: lint format-check typecheck test ## Full quality gate (CI)

# ─── Database ──────────────────────────────────────────────────────────────────
db-up: ## Start Postgres (and cache) containers
	docker compose up -d db cache

db-down: ## Stop database containers
	docker compose down

migrate: ## Apply all migrations
	cd backend && $(ALEMBIC) upgrade head

migration: ## Create a new autogenerated migration: make migration m="add columns"
	cd backend && $(ALEMBIC) revision --autogenerate -m "$(m)"

migration-empty: ## Create an empty migration: make migration-empty m="seed baseline"
	cd backend && $(ALEMBIC) revision -m "$(m)"

# ─── Docker ────────────────────────────────────────────────────────────────────
docker-up: ## Build and start the full stack
	docker compose up -d --build

docker-down: ## Stop the full stack (keeps volumes)
	docker compose down

docker-down-volumes: ## Stop the stack and delete volumes (destructive)
	docker compose down -v

# ─── ETL ───────────────────────────────────────────────────────────────────────
etl-run: ## Run a pipeline: make etl-run pipeline=aiq_cutoffs year=2025
	$(PYTHONPATH_BACKEND) $(BIN)/python etl/run.py --pipeline $(pipeline) --year $(year)

clean: ## Remove caches and build artifacts
	rm -rf .pytest_cache .ruff_cache .mypy_cache htmlcov build dist
	find . -type d -name __pycache__ -prune -exec rm -rf {} +
